# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.38', '5.36', '5.34' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: perl-version
        run: perl -V
      - name: install-dzil
        run: cpanm -n Dist::Zilla
      - name: install-authordeps
        run: dzil authordeps --missing | cpanm -n
      - name: install-deps
        run: dzil listdeps --missing | grep -v tidied | cpanm -n
      - name: run-tests
        run: dzil test
